git:
  commitMessages: "chore: release v${version}"

hooks:
  - before:npm:release: "echo \"//registry.npmjs.org/:_authToken=$NPM_TOKEN\" > .npmrc"

plugins:
  "@release-it/conventional-changelog":
    preset:
      name: conventionalcommits
      types:
        - type: feat
          section: 🚀 Features
        - type: fix
          section: 🧰 Bug Fixes
        - type: chore
          section: 🔫 Chores
        - type: docs
          section: 🌠 Docs
        - type: ci
          section: 🗳️ CICD
        - {}
    infile: CHANGELOG.md
