git:
  commitMessage: "🚀 Release v${version} [skip ci]"

plugins:
  "@release-it/conventional-changelog":
    preset:
      name: conventionalcommits
      types:
        - type: feat
          section: 🚀 Features
        - type: fix
          section: 🧰 Bug Fixes
        - type: chore
          section: 🔫 Chores
        - type: docs
          section: 🌠 Docs
        - type: ci
          section: 🗳️ CICD
        - {}
    infile: CHANGELOG.md
