language: node_js

node_js:
  - 14

cache: yarn

branches:
  only:
    - main

install:
  - yarn install --frozen-lockfile

script:
  - yarn build
  - yarn test --coverage --ci

deploy:
  skip_cleanup: true
  provider: script
  script: echo ${NPM_PASSWORD} && yarn release --ci --npm.otp=${NPM_PASSWORD}
  on:
    branch: main
