language: node_js

node_js:
  - 14

cache: yarn

branches:
  only:
    - main

install:
  - yarn install --frozen-lockfile

script:
  - yarn build

before_deploy: yarn release --ci --no-npm --no-git

deploy:
  provider: npm
  email: yokiyuqian@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: main
