language: node_js

node_js:
  - 14

cache: npm

branches:
  only:
    - main

install:
  - npm ci

script:
  - npm build

after_script:
  - git remote rm origin
  - git remote add origin https://iamyoki:${GITHUB_TOKEN}@github.com/iamyoki/playwright-watch.git
  - git symbolic-ref HEAD refs/heads/main

after_success: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

deploy:
  provider: script
  script: npm run release --ci
  skip_cleanup: true
  on:
    branch: main
