language: node_js

node_js:
  - 14

cache: yarn

branches:
  only:
    - main

install:
  - yarn install --frozen-lockfile

script:
  - yarn build

after_success: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

deploy:
  provider: script
  script: cat .npmrc && yarn release --ci
  skip_cleanup: true
  on:
    branch: main
