language: node_js

node_js:
  - 14

cache: yarn

branches:
  only:
    - main

env:
  - HUSKY=0

install:
  - yarn install --frozen-lockfile

script:
  - yarn build

after_success: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

before_deploy:
  - git config --global user.name "Travis CI"
  - git config --global user.email "yokiyuqian@gmail.com"
  - git remote set-url origin https://iamyoki:${GITHUB_TOKEN}@github.com/iamyoki/playwright-watch.git
  - git symbolic-ref HEAD refs/heads/main

deploy:
  provider: script
  script: npm run release -- --ci
  skip_cleanup: true
  on:
    branch: main
