language: node_js

node_js:
  - 14

cache: yarn

branches:
  only:
    - main

install:
  - yarn install --frozen-lockfile

script:
  - yarn build
  - yarn test --coverage --ci

deploy:
  provider: script
  script: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc && cat .npmrc && yarn release --ci
  on:
    branch: main
    skip_cleanup: true
